### ISSUE TITLE
Missing Client Id parameter

### ISSUE THREAD

**Issue by vaverix** [joeleisner/twitch-stream-check#1]
Hello there.

Twitch API now requires Client Id parameter when performing any request to their interface.
More informations here: [https://discuss.dev.twitch.tv/t/client-id-requirement-faqs/6108](url).

Thanks.

**Comment by joeleisner** [comment]
Hey, vaverix!

I noticed the API change a while back, but unfortunately, registering this Node CLI is nearly impossible. Twitch requests some type of point-of-origin, and with the CLI being distributed to hundreds of machines, this simply cannot be done.

If I notice an update to the API, or figure out way to register my CLI, I will certainly do so ASAP. But for the time being, this little tool will stay broken :(

Sorry for the inconvenience; Hopefully I can figure out a solution soon. Thanks!

**Comment by joeleisner** [comment]
Hey, vaverix!

Just thought I'd drop by and let you know that version 1.2.0 of twitch-stream-check has now been released, which fixes the issue of the "Client-ID" not being set. Thought the situation was more difficult than it actually was; it was a super simple fix and I'm sorry for the long wait. You can check it out here: https://www.npmjs.com/package/twitch-stream-check

This issue will now be closed. Thanks for the help!
