### ISSUE TITLE
any way to check if the channel exists or not?

### ISSUE THREAD

**Issue by markito12** [joeleisner/twitch-stream-check#6]

**Comment by joeleisner** [comment]
Hey, @markito12 !

As it stands now, if you try to look up info on a user that does not exist, it will return "[usename] is not streaming!" just as it does for valid users that are not streaming. I'm going to look into whether or not it's possible to deliver an alternative message for invalid users, and if so, it will be included with the 2.0.0 release.

**Comment by joeleisner** [comment]
Hey, @markito12 !

I was able accomplish what you were asking for! If a user does not exist, it will return "[username] does not exist!" now. Hopefully this will alleviate some issues in the future! Unfortunately, this change will be included on the 2.0.0 release, which uses Twitch's new API; Currently, there is only one flag I cannot get from the new API, so until that is resolved, the 2.0.0 release must wait.

Let me know if you have any questions or concerns!

**Comment by markito12** [comment]
Thank you so much!!!!

**Comment by joeleisner** [comment]
No problem! Glad you're using my little CLI, and hopefully the 2.0.0 release will be out sooner than later.

**Comment by markito12** [comment]
its a huge project btw! probably for an entire country so thanks for providing me the tools!

**Comment by markito12** [comment]
also would be great if u add a javascript guide ;)
